import os
import re

# LLM generated dictionary of all the synopsys, descriptions, and string arrays in dataEs.ts
translations = {
    "fr": {
        "Paul Gauguin, enfermo y en sus últimos días, es sometido a juicio por las autoridades francesas en Tahití mientras se obsesiona con pintar su última gran obra.": "Paul Gauguin, malade et à la fin de ses jours, est jugé par les autorités françaises à Tahiti tout en étant obsédé par la réalisation de sa dernière grande œuvre.",
        "Gauguin enfrenta un juicio en Tahití mientras pinta su última obra.": "Gauguin fait face à un procès à Tahiti pendant qu'il peint sa dernière œuvre.",
        "Una poderosa exploración visual de un capítulo poco conocido en la vida del famoso pintor.": "Une puissante exploration visuelle d'un chapitre méconnu de la vie du célèbre peintre.",
        "Tras el asesinato de un millonario, su guardaespaldas descubre a tres sospechosos en la casa mientras desaparece un valioso maletín.": "Après l'assassinat d'un millionnaire, son garde du corps découvre trois suspects dans la maison alors qu'une mallette de valeur disparaît.",
        "Un guardaespaldas encuentra a tres sospechosos de asesinato y un maletín perdido.": "Un garde du corps trouve trois suspects de meurtre et une mallette disparue.",
        "Aporta una sofisticada estructura narrativa al género del thriller en Latinoamérica.": "Apporte une structure narrative sophistiquée au genre du thriller en Amérique latine.",
        "Tras ser descubierta disfrazándose de Virgen, Amparo huye por miedo a su padre del internado de monjas donde la acogían. Llega a un barrio marginado de Medellín a vivir de \\\"arrimada\\\" donde su hermana. Forzada a convertirse en la mujer del Animal, sobrevive y busca salvar a su hija.": "Après avoir été découverte se déguisant en Vierge, Amparo s'enfuit du pensionnat de religieuses par peur de son père. Elle arrive dans un quartier marginal de Medellín. Forcée de devenir la femme de l'Animal, elle survit et cherche à sauver sa fille.",
        "Forzada a convivir con 'el Animal', una mujer lucha por sobrevivir y proteger a su hija.": "Forcée de vivre avec 'l'Animal', une femme lutte pour survivre et protéger sa fille.",
        "Un retrato crudo y dolorosamente realista sobre la violencia y supervivencia.": "Un portrait brut et douloureusement réaliste de la violence et de la survie.",
        "James regresa a su América Latina natal después de 30 años para extraer un órgano de una víctima. El viaje lo obliga a revivir su violento pasado.": "James retourne dans son Amérique latine natale après 30 ans pour prélever un organe d'une victime. Le voyage le force à revivre son passé violent.",
        "Un hombre regresa a Latinoamérica para tomar un órgano, enfrentando su pasado.": "Un homme retourne en Amérique latine pour prendre un organe, affrontant son passé.",
        "Expone realidades sociales crudas a través de una narrativa atrapante.": "Expose des réalités sociales dures à travers une narration captivante.",
        "Dos mujeres de diferentes clases sociales se encuentran durante un desastre natural que se lleva sus pasados, uniéndolas como inmigrantes de la noche a la mañana.": "Deux femmes de différentes classes sociales se rencontrent lors d'une catastrophe naturelle qui emporte leur passé, les unissant comme immigrantes du jour au lendemain.",
        "Un desastre une a dos mujeres muy diferentes como inmigrantes de la noche a la mañana.": "Une catastrophe unit deux femmes très différentes comme immigrantes du jour au lendemain.",
        "Un emotivo retrato de pérdida y resiliencia en el cine latinoamericano.": "Un portrait émouvant de perte et de résilience dans le cinéma latino-américain.",
        "Habiendo sobrevivido a su propia adicción, un hombre lucha por preservar su cordura y salvar a su familia.": "Ayant survécu à sa propre dépendance, un homme lutte pour préserver sa santé mentale et sauver sa famille.",
        "Un hombre batalla para mantener la cordura y salvar a su familia.": "Un homme se bat pour maintenir sa santé mentale et sauver sa famille.",
        "Muestra una narrativa emocional e íntima junto a actuaciones brillantes.": "Montre une narration émotionnelle et intime avec des performances brillantes.",
        "La vida pacífica de un hombre se ve alterada cuando una niña de 13 años se cruza en el camino de su hijo y comienza a extorsionarlos a ambos.": "La vie paisible d'un homme est bouleversée lorsqu'une fille de 13 ans croise le chemin de son fils et commence à les extorquer tous les deux.",
        "Una niña de 13 años extorsiona a un hombre pacífico y a su hijo.": "Une fille de 13 ans extorque un homme paisible et son fils.",
        "Una clase maestra de cómo construir tensión a partir de situaciones cotidianas.": "Une masterclass sur la façon de construire la tension à partir de situations quotidiennes.",
        "La historia real de un policía celoso y su joven esposa que viven en un barrio marginal en Sudamérica.": "L'histoire vraie d'un policier jaloux et de sa jeune épouse vivant dans un quartier marginal en Amérique du Sud.",
        "La historia basada en hechos reales de un policía celoso y su joven esposa.": "L'histoire basée sur des faits réels d'un policier jaloux et de sa jeune épouse.",
        "Una de las películas venezolanas más exitosas de todos los tiempos, que expone el machismo y el poder.": "L'un des films vénézuéliens les plus réussis de tous les temps, exposant le machisme et le pouvoir.",
        "Tres jóvenes que conocen a un inmigrante rumano en Madrid deciden viajar hacia el mar para escapar de las miserias de sus vidas.": "Trois jeunes qui rencontrent un immigrant roumain à Madrid décident de voyager vers la mer pour échapper aux misères de leur vie.",
        "Tres jóvenes viajan hacia el mar para escapar de sus vidas miserables.": "Trois jeunes voyagent vers la mer pour échapper à leurs vies misérables.",
        "Captura la rebelión y vulnerabilidad de la juventud con un crudo realismo.": "Capture la rébellion et la vulnérabilité de la jeunesse avec un réalisme brut.",
        "De cómo una generación de cineastas está redefiniendo la narrativa colombiana, saliendo de la sombra de García Márquez hacia un territorio audaz y nuevo.": "Comment une génération de cinéastes redéfinit la narration colombienne, sortant de l'ombre de García Márquez vers un territoire audacieux et nouveau.",
        "El autor brasileño discute Fragmentos de Luz, la transformación de Recife, y por qué los edificios cuentan historias que la gente calla.": "L'auteur brésilien discute des Fragments de Lumière, de la transformation de Recife et de la raison pour laquelle les bâtiments racontent des histoires que les gens taisent.",
        "De espectadores pasivos a participantes activos: cómo los canales impulsados por la comunidad crean un nuevo valor para el cine.": "Des spectateurs passifs aux participants actifs : comment les chaînes animées par la communauté créent une nouvelle valeur pour le cinéma.",
        "El director guatemalteco comparte su enfoque sobre la representación, la colaboración y la responsabilidad de contar estas historias.": "Le réalisateur guatémaltèque partage son approche de la représentation, de la collaboration et de la responsabilité de raconter ces histoires.",
        "La Nueva Ola del Cine Colombiano: Más allá del Realismo Mágico": "La Nouvelle Vague du Cinéma Colombien : Au-delà du Réalisme Magique",
        "Kleber Mendonça Filho: 'La arquitectura es memoria hecha visible'": "Kleber Mendonça Filho : 'L'architecture est la mémoire rendue visible'",
        "Cómo los Canales de AGARRA están Cambiando la Distribución": "Comment les Chaînes AGARRA Changent la Distribution",
        "Notas de Director: Jayro Bustamante al Filmar Historias Indígenas": "Notes du Réalisateur : Jayro Bustamante Filme des Histoires Indigènes",
        "PDF exclusivo descargable del guion original con notas al margen.": "PDF exclusif téléchargeable du scénario original avec des notes en marge.",
        "Entrada digital gratuita para la próxima watch party de la película.": "Billet numérique gratuit pour la prochaine watch party du film.",
        "Imágenes de detrás de cámara en alta resolución listas para descargar.": "Images des coulisses en haute résolution prêtes à être téléchargées.",
        "Edición limitada del póster oficial enviado a tu domicilio.": "Édition limitée de l'affiche officielle expédiée à votre domicile.",
        "Únete a Canales Comunitarios gratuitamente": "Rejoignez des Chaînes Communautaires gratuitement",
        "Gana recompensas base": "Gagnez des récompenses de base",
        "Participa en discusiones": "Participez aux discussions",
        "Compra entradas individuales": "Achetez des billets individuels",
        "Acceso ilimitado a todos los Canales de Películas": "Accès illimité à toutes les Chaînes de Films",
        "Pase VIP a eventos en vivo y Watch Parties": "Pass VIP pour des événements en direct et Check Parties",
        "Acesso Exclusivo Anticipado a nuevos estrenos": "Accès Exclusif Anticipé aux nouvelles sorties",
        "Vota en el Fondo para Directores": "Votez dans le Fonds pour Réalisateurs",
        "Todo lo del Pase Premium": "Tout du Pass Premium",
        "Garantía de recompensas raras": "Garantie de récompenses rares",
        "Invitación a eventos físicos de la industria": "Invitation à des événements physiques de l'industrie",
        "Crédito de agradecimiento en futuros fondos": "Crédit de remerciement dans de futurs fonds",
        "Merch oficial enviado anualmente": "Produits officiels expédiés annuellement"
    },
    "de": {
        "Paul Gauguin, enfermo y en sus últimos días, es sometido a juicio por las autoridades francesas en Tahití mientras se obsesiona con pintar su última gran obra.": "Paul Gauguin, krank und am Ende seiner Tage, wird von den französischen Behörden auf Tahiti vor Gericht gestellt, während er besessen davon ist, sein letztes großes Werk zu malen.",
        "Gauguin enfrenta un juicio en Tahití mientras pinta su última obra.": "Gauguin steht auf Tahiti vor Gericht, während er sein letztes Werk malt.",
        "Una poderosa exploración visual de un capítulo poco conocido en la vida del famoso pintor.": "Eine kraftvolle visuelle Erkundung eines wenig bekannten Kapitels im Leben des berühmten Malers.",
        "Tras el asesinato de un millonario, su guardaespaldas descubre a tres sospechosos en la casa mientras desaparece un valioso maletín.": "Nach der Ermordung eines Millionärs entdeckt sein Leibwächter drei Verdächtige im Haus, während eine wertvolle Aktentasche verschwindet.",
        "Un guardaespaldas encuentra a tres sospechosos de asesinato y un maletín perdido.": "Ein Leibwächter findet drei Mordverdächtige und eine verlorene Aktentasche.",
        "Aporta una sofisticada estructura narrativa al género del thriller en Latinoamérica.": "Bringt eine ausgeklügelte narrative Struktur in das Thriller-Genre in Lateinamerika.",
        "Tras ser descubierta disfrazándose de Virgen, Amparo huye por miedo a su padre del internado de monjas donde la acogían. Llega a un barrio marginado de Medellín a vivir de \\\"arrimada\\\" donde su hermana. Forzada a convertirse en la mujer del Animal, sobrevive y busca salvar a su hija.": "Nachdem sie dabei entdeckt wurde, wie sie sich als Jungfrau verkleidete, flieht Amparo aus Angst vor ihrem Vater aus dem Nonneninternat. Gezwungen, die Frau des Tieres zu werden, überlebt sie und versucht, ihre Tochter zu retten.",
        "Forzada a convivir con 'el Animal', una mujer lucha por sobrevivir y proteger a su hija.": "Gezwungen, mit 'dem Tier' zu leben, kämpft eine Frau ums Überleben und um den Schutz ihrer Tochter.",
        "Un retrato crudo y dolorosamente realista sobre la violencia y supervivencia.": "Ein rohes und schmerzhaft realistisches Porträt über Gewalt und Überleben.",
        "James regresa a su América Latina natal después de 30 años para extraer un órgano de una víctima. El viaje lo obliga a revivir su violento pasado.": "James kehrt nach 30 Jahren in sein Heimatland Lateinamerika zurück, um einem Opfer ein Organ zu entnehmen.",
        "Un hombre regresa a Latinoamérica para tomar un órgano, enfrentando su pasado.": "Ein Mann kehrt nach Lateinamerika zurück, um ein Organ zu nehmen und sich seiner Vergangenheit zu stellen.",
        "Expone realidades sociales crudas a través de una narrativa atrapante.": "Deck auf raue soziale Realitäten durch eine fesselnde Erzählung auf.",
        "Dos mujeres de diferentes clases sociales se encuentran durante un desastre natural que se lleva sus pasados, uniéndolas como inmigrantes de la noche a la mañana.": "Zwei Frauen aus unterschiedlichen sozialen Schichten treffen während einer Naturkatastrophe aufeinander, die sie über Nacht als Einwanderer vereint.",
        "Un desastre une a dos mujeres muy diferentes como inmigrantes de la noche a la mañana.": "Eine Katastrophe vereint zwei sehr unterschiedliche Frauen über Nacht als Einwanderer.",
        "Un emotivo retrato de pérdida y resiliencia en el cine latinoamericano.": "Ein emotionales Porträt von Verlust und Resilienz im lateinamerikanischen Kino.",
        "Habiendo sobrevivido a su propia adicción, un hombre lucha por preservar su cordura y salvar a su familia.": "Nachdem er seine eigene Sucht überlebt hat, kämpft ein Mann darum, seinen Verstand zu bewahren und seine Familie zu retten.",
        "Un hombre batalla para mantener la cordura y salvar a su familia.": "Ein Mann kämpft darum, seinen Verstand zu behalten und seine Familie zu retten.",
        "Muestra una narrativa emocional e íntima junto a actuaciones brillantes.": "Zeigt eine emotionale und intime Erzählung zusammen mit brillanten schauspielerischen Leistungen.",
        "La vida pacífica de un hombre se ve alterada cuando una niña de 13 años se cruza en el camino de su hijo y comienza a extorsionarlos a ambos.": "Das friedliche Leben eines Mannes wird auf den Kopf gestellt, als ein 13-jähriges Mädchen den Weg seines Sohnes kreuzt und beginnt, beide zu erpressen.",
        "Una niña de 13 años extorsiona a un hombre pacífico y a su hijo.": "Ein 13-jähriges Mädchen erpresst einen friedlichen Mann und seinen Sohn.",
        "Una clase maestra de cómo construir tensión a partir de situaciones cotidianas.": "Eine Meisterklasse, wie man Spannung aus Alltagssituationen aufbaut.",
        "La historia real de un policía celoso y su joven esposa que viven en un barrio marginal en Sudamérica.": "Die wahre Geschichte eines eifersüchtigen Polizisten und seiner jungen Frau, die in einem Slum in Südamerika leben.",
        "La historia basada en hechos reales de un policía celoso y su joven esposa.": "Erforscht die auf wahren Begebenheiten beruhende Geschichte eines eifersüchtigen Polizisten.",
        "Una de las películas venezolanas más exitosas de todos los tiempos, que expone el machismo y el poder.": "Einer der erfolgreichsten venezolanischen Filme aller Zeiten, der Machismus und Macht aufdeckt.",
        "Tres jóvenes que conocen a un inmigrante rumano en Madrid deciden viajar hacia el mar para escapar de las miserias de sus vidas.": "Drei Jugendliche, die einen rumänischen Einwanderer in Madrid treffen, beschließen, ans Meer zu reisen, um dem Elend ihres Lebens zu entfliehen.",
        "Tres jóvenes viajan hacia el mar para escapar de sus vidas miserables.": "Drei Jugendliche reisen ans Meer, um ihrem miserablen Leben zu entfliehen.",
        "Captura la rebelión y vulnerabilidad de la juventud con un crudo realismo.": "Fängt die Rebellion und Verletzlichkeit der Jugend mit einem rauen Realismus ein.",
        "De cómo una generación de cineastas está redefiniendo la narrativa colombiana, saliendo de la sombra de García Márquez hacia un territorio audaz y nuevo.": "Wie eine Generation von Filmemachern die kolumbianische Erzählung neu definiert und aus dem Schatten von García Márquez in neues Territorium tritt.",
        "El autor brasileño discute Fragmentos de Luz, la transformación de Recife, y por qué los edificios cuentan historias que la gente calla.": "Der brasilianische Autor diskutiert Fragmente des Lichts, die Transformation von Recife und warum Gebäude Geschichten erzählen.",
        "De espectadores pasivos a participantes activos: cómo los canales impulsados por la comunidad crean un nuevo valor para el cine.": "Von passiven Zuschauern zu aktiven Teilnehmern: Wie von der Community getragene Kanäle neuen Wert für das Kino schaffen.",
        "El director guatemalteco comparte su enfoque sobre la representación, la colaboración y la responsabilidad de contar estas historias.": "Der guatemaltekische Regisseur teilt seinen Ansatz zur Repräsentation, Zusammenarbeit und der Verantwortung.",
        "La Nueva Ola del Cine Colombiano: Más allá del Realismo Mágico": "Die neue Welle des kolumbianischen Kinos: Jenseits des Magischen Realismus",
        "Kleber Mendonça Filho: 'La arquitectura es memoria hecha visible'": "Kleber Mendonça Filho: 'Architektur ist sichtbar gemachte Erinnerung'",
        "Cómo los Canales de AGARRA están Cambiando la Distribución": "Wie die Kanäle von AGARRA die Distribution verändern",
        "Notas de Director: Jayro Bustamante al Filmar Historias Indígenas": "Regienotizen: Jayro Bustamante filmt indigene Geschichten",
        "PDF exclusivo descargable del guion original con notas al margen.": "Exklusives herunterladbares PDF des Originaldrehbuchs mit Randnotizen.",
        "Entrada digital gratuita para la próxima watch party de la película.": "Kostenloses digitales Ticket für die nächste Watch-Party des Films.",
        "Imágenes de detrás de cámara en alta resolución listas para descargar.": "Hinter den Kulissen-Bilder in hoher Auflösung zum Herunterladen.",
        "Edición limitada del póster oficial enviado a tu domicilio.": "Limitierte Auflage des offiziellen Posters, das an Ihre Adresse gesendet wird.",
        "Únete a Canales Comunitarios gratuitamente": "Tritt kostenlosen Community-Kanälen bei",
        "Gana recompensas base": "Gewinne Basisbelohnungen",
        "Participa en discusiones": "Nimm an Diskussionen teil",
        "Compra entradas individuales": "Kaufe Einzeltickets",
        "Acceso ilimitado a todos los Canales de Películas": "Unbegrenzter Zugang zu allen Filmkanälen",
        "Pase VIP a eventos en vivo y Watch Parties": "VIP-Pass für Live-Events und Watch Partys",
        "Acesso Exclusivo Anticipado a nuevos estrenos": "Exklusiver Frühzugang zu neuen Veröffentlichungen",
        "Vota en el Fondo para Directores": "Stimme im Fonds für Regisseure ab",
        "Todo lo del Pase Premium": "Alles aus dem Premium Pass",
        "Garantía de recompensas raras": "Garantie für seltene Belohnungen",
        "Invitación a eventos físicos de la industria": "Einladung zu physischen Branchenveranstaltungen",
        "Crédito de agradecimiento en futuros fondos": "Dankeschön-Kredit in zukünftigen Fonds",
        "Merch oficial enviado anualmente": "Offizielles Merchandising jährlich versendet"
    },
    "it": {
        "Paul Gauguin, enfermo y en sus últimos días, es sometido a juicio por las autoridades francesas en Tahití mientras se obsesiona con pintar su última gran obra.": "Paul Gauguin, malato e nei suoi ultimi giorni, viene processato dalle autorità francesi a Tahiti mentre è ossessionato dal dipingere la sua ultima grande opera.",
        "Gauguin enfrenta un juicio en Tahití mientras pinta su última obra.": "Gauguin affronta un processo a Tahiti mentre dipinge la sua ultima opera.",
        "Una poderosa exploración visual de un capítulo poco conocido en la vida del famoso pintor.": "Una potente esplorazione visiva di un capitolo poco noto della vita del famoso pittore.",
        "Tras el asesinato de un millonario, su guardaespaldas descubre a tres sospechosos en la casa mientras desaparece un valioso maletín.": "Dopo l'omicidio di un milionario, la sua guardia del corpo scopre tre sospetti nella casa mentre scompare una preziosa valigetta.",
        "Un guardaespaldas encuentra a tres sospechosos de asesinato y un maletín perdido.": "Una guardia del corpo trova tre sospetti di omicidio e una valigetta smarrita.",
        "Aporta una sofisticada estructura narrativa al género del thriller en Latinoamérica.": "Aggiunge una sofisticata struttura narrativa al genere thriller in America Latina.",
        "Tras ser descubierta disfrazándose de Virgen, Amparo huye por miedo a su padre del internado de monjas donde la acogían. Llega a un barrio marginado de Medellín a vivir de \\\"arrimada\\\" donde su hermana. Forzada a convertirse en la mujer del Animal, sobrevive y busca salvar a su hija.": "Dopo essere stata scoperta a travestirsi da Vergine, Amparo fugge per paura di suo padre dal collegio. Forzata a diventare la donna dell'Animale, sopravvive e cerca di salvare sua figlia.",
        "Forzada a convivir con 'el Animal', una mujer lucha por sobrevivir y proteger a su hija.": "Costretta a convivere con 'l'Animale', una donna lotta per sopravvivere e proteggere sua figlia.",
        "Un retrato crudo y dolorosamente realista sobre la violencia y supervivencia.": "Un ritratto crudo e dolorosamente realistico sulla violenza e la sopravvivenza.",
        "James regresa a su América Latina natal después de 30 años para extraer un órgano de una víctima. El viaje lo obliga a revivir su violento pasado.": "James torna in America Latina dopo 30 anni per prelevare un organo da una vittima. Il viaggio lo costringe a rivivere il suo passato violento.",
        "Un hombre regresa a Latinoamérica para tomar un órgano, enfrentando su pasado.": "Un uomo torna in America Latina per prelevare un organo, affrontando il passato.",
        "Expone realidades sociales crudas a través de una narrativa atrapante.": "Rivela le crude realtà sociali attraverso una narrazione avvincente.",
        "Dos mujeres de diferentes clases sociales se encuentran durante un desastre natural que se lleva sus pasados, uniéndolas como inmigrantes de la noche a la mañana.": "Due donne di classi sociali diverse si incontrano durante un disastro naturale che si porta via il loro passato, unendole come immigrate da un giorno all'altro.",
        "Un desastre une a dos mujeres muy diferentes como inmigrantes de la noche a la mañana.": "Un disastro unisce due donne molto diverse come immigrate da un giorno all'altro.",
        "Un emotivo retrato de pérdida y resiliencia en el cine latinoamericano.": "Un emozionante ritratto di perdita e resilienza nel cinema latinoamericano.",
        "Habiendo sobrevivido a su propia adicción, un hombre lucha por preservar su cordura y salvar a su familia.": "Essendo sopravvissuto alla propria dipendenza, un uomo lotta per preservare la propria sanità mentale e salvare la propria famiglia.",
        "Un hombre batalla para mantener la cordura y salvar a su familia.": "Un uomo combatte per mantenere la sua sanità mentale e salvare la sua famiglia.",
        "Muestra una narrativa emocional e íntima junto a actuaciones brillantes.": "Mostra una narrazione emotiva e intima insieme a prestazioni eccezionali.",
        "La vida pacífica de un hombre se ve alterada cuando una niña de 13 años se cruza en el camino de su hijo y comienza a extorsionarlos a ambos.": "La vita pacifica di un uomo viene alterata quando una ragazza di 13 anni incrocia la strada di suo figlio e inizia a estorcere denaro a entrambi.",
        "Una niña de 13 años extorsiona a un hombre pacífico y a su hijo.": "Una ragazzina di 13 anni estorce a un uomo pacifico e a suo figlio.",
        "Una clase maestra de cómo construir tensión a partir de situaciones cotidianas.": "Una lezione magistrale su come costruire tensione da situazioni quotidiane.",
        "La historia real de un policía celoso y su joven esposa que viven en un barrio marginal en Sudamérica.": "La vera storia di un poliziotto geloso e della sua giovane moglie che vivono in un quartiere povero in Sudamerica.",
        "La historia basada en hechos reales de un policía celoso y su joven esposa.": "La storia basata su eventi reali di un poliziotto geloso e di sua giovane moglie.",
        "Una de las películas venezolanas más exitosas de todos los tiempos, que expone el machismo y el poder.": "Uno dei film venezuelani di maggior successo di tutti i tempi, che espone machismo e potere.",
        "Tres jóvenes que conocen a un inmigrante rumano en Madrid deciden viajar hacia el mar para escapar de las miserias de sus vidas.": "Tre giovani che incontrano un immigrato rumeno a Madrid decidono di viaggiare verso il mare per fuggire dalla miseria delle loro vite.",
        "Tres jóvenes viajan hacia el mar para escapar de sus vidas miserables.": "Tre giovani viaggiano verso il mare per fuggire dalle loro miserabili vite.",
        "Captura la rebelión y vulnerabilidad de la juventud con un crudo realismo.": "Cattura la ribellione e la vulnerabilità della giovinezza con un crudo realismo.",
        "De cómo una generación de cineastas está redefiniendo la narrativa colombiana, saliendo de la sombra de García Márquez hacia un territorio audaz y nuevo.": "Di come una generazione di registi stia ridefinendo la narrazione colombiana, uscendo dall'ombra di García Márquez verso territori nuovi.",
        "El autor brasileño discute Fragmentos de Luz, la transformación de Recife, y por qué los edificios cuentan historias que la gente calla.": "L'autore brasiliano discute Frammenti di Luce, la trasformazione di Recife, e perché gli edifici raccontano storie che le persone tacciono.",
        "De espectadores pasivos a participantes activos: cómo los canales impulsados por la comunidad crean un nuevo valor para el cine.": "Da spettatori passivi a partecipanti attivi: come i canali guidati dalla comunità creano nuovo valore per il cinema.",
        "El director guatemalteco comparte su enfoque sobre la representación, la colaboración y la responsabilidad de contar estas historias.": "Il regista guatemalteco condivide il suo approccio sulla rappresentanza e sulla collaborazione.",
        "La Nueva Ola del Cine Colombiano: Más allá del Realismo Mágico": "La Nuova Onda del Cinema Colombiano: Oltre il Realismo Magico",
        "Kleber Mendonça Filho: 'La arquitectura es memoria hecha visible'": "Kleber Mendonça Filho: 'L'architettura è memoria resa visibile'",
        "Cómo los Canales de AGARRA están Cambiando la Distribución": "Come i Canali AGARRA stanno Cambiando la Distribuzione",
        "Notas de Director: Jayro Bustamante al Filmar Historias Indígenas": "Appunti del Regista: Jayro Bustamante Filmando Storie Indigene",
        "PDF exclusivo descargable del guion original con notas al margen.": "PDF esclusivo scaricabile dello script originale con annotazioni.",
        "Entrada digital gratuita para la próxima watch party de la película.": "Biglietto digitale gratuito per la prossima watch party del film.",
        "Imágenes de detrás de cámara en alta resolución listas para descargar.": "Immagini dietro le quinte in alta risoluzione pronte per il download.",
        "Edición limitada del póster oficial enviado a tu domicilio.": "Edizione limitata del poster ufficiale inviato a casa tua.",
        "Únete a Canales Comunitarios gratuitamente": "Unisciti ai Canali della Community gratuitamente",
        "Gana recompensas base": "Guadagna premi base",
        "Participa en discusiones": "Partecipa alle discussioni",
        "Compra entradas individuales": "Acquista biglietti individuali",
        "Acceso ilimitado a todos los Canales de Películas": "Accesso illimitato a tutti i Canali di Film",
        "Pase VIP a eventos en vivo y Watch Parties": "Pass VIP per eventi dal vivo e Watch Parties",
        "Acesso Exclusivo Anticipado a nuevos estrenos": "Accesso Esclusivo Anticipato alle nuove uscite",
        "Vota en el Fondo para Directores": "Vota nel Fondo per Registri",
        "Todo lo del Pase Premium": "Tutto del Pass Premium",
        "Garantía de recompensas raras": "Garanzia di premi rari",
        "Invitación a eventos físicos de la industria": "Invito a eventi fisici del settore",
        "Crédito de agradecimiento en futuros fondos": "Credito di ringraziamento nei fondi futuri",
        "Merch oficial enviado anualmente": "Merchandising ufficiale inviato annualmente"
    },
    "pt": {
        "Paul Gauguin, enfermo y en sus últimos días, es sometido a juicio por las autoridades francesas en Tahití mientras se obsesiona con pintar su última gran obra.": "Paul Gauguin, doente e em seus últimos dias, é levado a julgamento pelas autoridades francesas no Taiti enquanto está obsecado em pintar sua última grande obra.",
        "Gauguin enfrenta un juicio en Tahití mientras pinta su última obra.": "Gauguin enfrenta um julgamento no Taiti enquanto pinta a sua última obra.",
        "Una poderosa exploración visual de un capítulo poco conocido en la vida del famoso pintor.": "Uma poderosa exploração visual de um capítulo pouco conhecido da vida do famoso pintor.",
        "Tras el asesinato de un millonario, su guardaespaldas descubre a tres sospechosos en la casa mientras desaparece un valioso maletín.": "Após o assassinato de um milionário, seu guarda-costas descobre três suspeitos na casa enquanto desaparece uma maleta valiosa.",
        "Un guardaespaldas encuentra a tres sospechosos de asesinato y un maletín perdido.": "Um guarda-costas encontra três suspeitos de assassinato e uma valise perdida.",
        "Aporta una sofisticada estructura narrativa al género del thriller en Latinoamérica.": "Traz uma estrutura narrativa sofisticada para o gênero de suspense na América Latina.",
        "Tras ser descubierta disfrazándose de Virgen, Amparo huye por miedo a su padre del internado de monjas donde la acogían. Llega a un barrio marginado de Medellín a vivir de \\\"arrimada\\\" donde su hermana. Forzada a convertirse en la mujer del Animal, sobrevive y busca salvar a su hija.": "Após ser descoberta se disfarçando de Virgem, Amparo foge por medo do seu pai do internato. Forçada a se tornar a mulher do Animal, sobrevive e busca salvar sua filha.",
        "Forzada a convivir con 'el Animal', una mujer lucha por sobrevivir y proteger a su hija.": "Forçada a conviver com 'o Animal', uma mulher luta por sobreviver e proteger sua filha.",
        "Un retrato crudo y dolorosamente realista sobre la violencia y supervivencia.": "Um retrato cru e dolorosamente realista sobre a violência e a sobrevivência.",
        "James regresa a su América Latina natal después de 30 años para extraer un órgano de una víctima. El viaje lo obliga a revivir su violento pasado.": "James volta à sua América Latina natal após 30 anos para extrair um órgão de uma vítima. A viagem o obriga a reviver seu passado violento.",
        "Un hombre regresa a Latinoamérica para tomar un órgano, enfrentando su pasado.": "Um homem volta à América Latina para tirar um órgão e enfrenta o passado.",
        "Expone realidades sociales crudas a través de una narrativa atrapante.": "Expõe realidades sociais duras através de uma narrativa cativante.",
        "Dos mujeres de diferentes clases sociales se encuentran durante un desastre natural que se lleva sus pasados, uniéndolas como inmigrantes de la noche a la mañana.": "Duas mulheres de diferentes classes sociais se encontram durante um desastre natural que leva seus passados.",
        "Un desastre une a dos mujeres muy diferentes como inmigrantes de la noche a la mañana.": "Um desastre une duas mulheres muito diferentes como imigrantes durante a noite.",
        "Un emotivo retrato de pérdida y resiliencia en el cine latinoamericano.": "Um emocionante retrato de perda e resiliência no cinema latino-americano.",
        "Habiendo sobrevivido a su propia adicción, un hombre lucha por preservar su cordura y salvar a su familia.": "Tendo sobrevivido ao seu próprio vício, um homem luta para preservar a sua sanidade e salvar a sua família.",
        "Un hombre batalla para mantener la cordura y salvar a su familia.": "Um homem luta para manter sua sanidade e salvar sua família.",
        "Muestra una narrativa emocional e íntima junto a actuaciones brillantes.": "Mostra uma narrativa emocional e íntima junto com atuações brilhantes.",
        "La vida pacífica de un hombre se ve alterada cuando una niña de 13 años se cruza en el camino de su hijo y comienza a extorsionarlos a ambos.": "A vida pacífica de um homem é alterada quando uma menina de 13 anos cruza o caminho do seu filho.",
        "Una niña de 13 años extorsiona a un hombre pacífico y a su hijo.": "Uma garota de 13 anos extorque um homem pacífico e seu filho.",
        "Una clase maestra de cómo construir tensión a partir de situaciones cotidianas.": "Uma aula mestre de como construir tensão a partir de situações diárias.",
        "La historia real de un policía celoso y su joven esposa que viven en un barrio marginal en Sudamérica.": "A verdadeira história de um policial ciumento e de sua esposa jovem vivendo numa favela na América do Sul.",
        "La historia basada en hechos reales de un policía celoso y su joven esposa.": "A história baseada em fatos de um policial ciumento e de sua esposa jovem.",
        "Una de las películas venezolanas más exitosas de todos los tiempos, que expone el machismo y el poder.": "Um dos filmes venezuelanos de maior sucesso de todos os tempos, que expõe machismo e poder.",
        "Tres jóvenes que conocen a un inmigrante rumano en Madrid deciden viajar hacia el mar para escapar de las miserias de sus vidas.": "Três jovens que encontram um imigrante romeno em Madri decidem viajar para o mar para escapar das misérias.",
        "Tres jóvenes viajan hacia el mar para escapar de sus vidas miserables.": "Três jovens viajam para o mar para escapar de suas vidas miseráveis.",
        "Captura la rebelión y vulnerabilidad de la juventud con un crudo realismo.": "Captura a rebelião e vulnerabilidade da juventude com um realismo puro.",
        "De cómo una generación de cineastas está redefiniendo la narrativa colombiana, saliendo de la sombra de García Márquez hacia un territorio audaz y nuevo.": "De como uma geração de cineastas está redefinindo a narrativa colombiana.",
        "El autor brasileño discute Fragmentos de Luz, la transformación de Recife, y por qué los edificios cuentan historias que la gente calla.": "O autor brasileiro discute Fragmentos de Luz, a transformação de Recife, e porquê os prédios contam histórias.",
        "De espectadores pasivos a participantes activos: cómo los canales impulsados por la comunidad crean un nuevo valor para el cine.": "De espectadores passivos a participantes ativos: como os canais impulsionados pela comunidade criam valor para o cinema.",
        "El director guatemalteco comparte su enfoque sobre la representación, la colaboración y la responsabilidad de contar estas historias.": "O diretor guatemalteco compartilha o seu foco na representação e na responsabilidade de contar essas histórias.",
        "La Nueva Ola del Cine Colombiano: Más allá del Realismo Mágico": "A Nova Onda do Cinema Colombiano: Além do Realismo Mágico",
        "Kleber Mendonça Filho: 'La arquitectura es memoria hecha visible'": "Kleber Mendonça Filho: 'Arquitetura é memória viva'",
        "Cómo los Canales de AGARRA están Cambiando la Distribución": "Como os Canais AGARRA estão Mudando a Distribuição",
        "Notas de Director: Jayro Bustamante al Filmar Historias Indígenas": "Anotações do Diretor: Jayro Bustamante Filmando Histórias Indígenas",
        "PDF exclusivo descargable del guion original con notas al margen.": "PDF exclusivo do roteiro para download com anotações nas bordas.",
        "Entrada digital gratuita para la próxima watch party de la película.": "Ingresso digital gratuito para a próxima watch party do filme.",
        "Imágenes de detrás de cámara en alta resolución listas para descargar.": "Imagens dos bastidores em alta resolução prontas para baixar.",
        "Edición limitada del póster oficial enviado a tu domicilio.": "Edição limitada do pôster oficial enviada para a sua casa.",
        "Únete a Canales Comunitarios gratuitamente": "Junte-se a Canais Comunitários gratuitamente",
        "Gana recompensas base": "Ganhe recompensas base",
        "Participa en discusiones": "Participe das discussões",
        "Compra entradas individuales": "Compre ingressos individuais",
        "Acceso ilimitado a todos los Canales de Películas": "Acesso ilimitado a todos os Canais de Filmes",
        "Pase VIP a eventos en vivo y Watch Parties": "Acesso VIP para eventos ao vivo e Watch Parties",
        "Acesso Exclusivo Anticipado a nuevos estrenos": "Acesso Exclusivo Antecipado aos novos lançamentos",
        "Vota en el Fondo para Directores": "Vota no Fundo para Diretores",
        "Todo lo del Pase Premium": "Tudo do Passe Premium",
        "Garantía de recompensas raras": "Garantia de recompensas raras",
        "Invitación a eventos físicos de la industria": "Convite a eventos físicos da indústria",
        "Crédito de agradecimiento en futuros fondos": "Crédito de agradecimento em futuros fundos",
        "Merch oficial enviado anualmente": "Merch oficial enviado anualmente"
    }
}

source_file = "src/lib/dataEs.ts"
with open(source_file, "r", encoding="utf-8") as f:
    orig_content = f.read()

for lang_code, dict_data in translations.items():
    content = orig_content
    for es_str, trans_str in dict_data.items():
        # we will simply replace the literal string including quotes
        # to prevent accidental partial replacements
        content = content.replace(f'"{es_str}"', f'"{trans_str}"')
    
    out_file = f"src/lib/data{lang_code.capitalize()}.ts"
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(content)

print("Mock data generated in 4 languages using LLM translations.")
